---
title: "Sentiment analysis of Amazon employee reviews in Glassdoor!"
author: "NickD - email: nickydyakov@gmail.com"
date: "2022-08-14"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(fig.width = 10, fig.asp = 0.618, out.width = "100%")
```

```{r message = FALSE, warning = FALSE}
# Loading the needed packages
library(tidyverse)
library(tidytext)
library(patchwork)
library(wordcloud)
library(reshape2)
```

```{r message = FALSE, warning = FALSE}
# Loading the data set
glassdoor <- read_csv("glassdoor.csv") %>% janitor::clean_names()
```

```{r include = FALSE}
# A little data clean up
amazon <- glassdoor %>% 
	filter(company_name == "Amazon") %>% drop_na() %>% 
  mutate(gd_ind_emp_status = fct_other(gd_ind_emp_status, keep = c("Current Employee", "Former Employee"))) %>% 
  mutate(gd_ind_position = fct_lump_min(gd_ind_position, min = 160), 
  			 gd_ind_location = fct_lump_min(gd_ind_location, min = 140),
  			 gd_ind_position = fct_recode(
  			 gd_ind_position, "Software Development Engineer" = "Current Employee>Software Development Engineer")) %>% 
  filter(!gd_ind_emp_status %in% ("Other"), !gd_ind_position %in% ("Other"), !gd_ind_location %in% ("Other"))
```

```{r include = FALSE}
# Selecting the variables of interest and tidying
tidy_amazon_pros <- amazon %>% select(gd_ind_emp_status, gd_ind_position, gd_ind_location, 40) %>% 
  unnest_tokens(word, gd_ind_review_pros)
tidy_amazon_cons <- amazon %>% select(gd_ind_emp_status, gd_ind_position, gd_ind_location, 41) %>% 
  unnest_tokens(word, gd_ind_review_cons)
```

```{r include = FALSE}
# ...and joining (binding) them
amazon_joined <- bind_rows(tidy_amazon_pros, tidy_amazon_cons) %>% drop_na()
```

```{r include = FALSE}
# Loading the stop-words data set and joining with Amazon data
data(stop_words)
amazon_joined <- amazon_joined %>%
  anti_join(stop_words, by = "word")
```

```{r include = FALSE}
# Loading the NRC lexicon for positive and negative sentiments
nrc_positive <- get_sentiments("nrc") %>%
  filter(sentiment == "positive")
nrc_negative <- get_sentiments("nrc") %>%
  filter(sentiment == "negative")
```

## Most popular positive and negative words as a whole

```{r fig 01, echo = FALSE, message = FALSE, warning = FALSE}
# Most popular positive words
p3<-amazon_joined %>%
  inner_join(nrc_positive, by = "word") %>%
  count(word, sort = TRUE) %>% 
  filter(n > 50) %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n)) +
  geom_col(fill = "#00BFC4") +
  labs(title = "Positive words", x = NULL) +
  theme(text = element_text(size = 16)) +
  coord_flip()

# Most popular negative words
p4<-amazon_joined %>%
  inner_join(nrc_negative, by = "word") %>%
  count(word, sort = TRUE) %>% 
  filter(n > 15) %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n)) +
  geom_col(fill = "#F8766D") +
  labs(title = "Negative words", x = NULL) +
  theme(text = element_text(size = 16)) +
  coord_flip()
p3+p4
```

## Most popular positive and negative words depending on employment status

```{r fig 02, echo = FALSE, message = FALSE, warning = FALSE}
# Most popular words among the current employees
p1<-amazon_joined %>%
  inner_join(nrc_positive, by = "word") %>%
  filter(gd_ind_emp_status == "Current Employee") %>% 
  count(word, sort = TRUE) %>%
  filter(n > 100) %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n)) +
  geom_col(fill = "#00BFC4") +
  labs(title = "Current employees'\npositive words", x = NULL) +
  theme(text = element_text(size = 16)) +
  coord_flip()
p2<-amazon_joined %>%
  inner_join(nrc_negative, by = "word") %>%
  filter(gd_ind_emp_status == "Current Employee") %>% 
  count(word, sort = TRUE) %>%
  filter(n > 15) %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n)) +
  geom_col(fill = "#F8766D") +
  labs(title = "Current employees'\nnegative words", x = NULL) +
  theme(text = element_text(size = 16)) +
  coord_flip()
p1+p2
```


```{r fig 03, echo = FALSE, message = FALSE, warning = FALSE}
# Most popular words among the former employees
p3<-amazon_joined %>%
  inner_join(nrc_positive, by = "word") %>%
  filter(gd_ind_emp_status == "Former Employee") %>% 
  count(word, sort = TRUE) %>%
  filter(n > 30) %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n)) +
  geom_col(fill = "#00BFC4") +
  labs(title = "Former employees'\npositive words", x = NULL) +
  theme(text = element_text(size = 16)) +
  coord_flip()
p4<-amazon_joined %>%
  inner_join(nrc_negative, by = "word") %>%
  filter(gd_ind_emp_status == "Former Employee") %>% 
  count(word, sort = TRUE) %>%
  filter(n > 5) %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n)) +
  geom_col(fill = "#F8766D") +
  labs(title = "Former employees'\nnegative words", x = NULL) +
  theme(text = element_text(size = 16)) +
  coord_flip()
p3+p4
```

## Most popular positive and negative words depending on employment position

```{r fig 04, echo = FALSE, message = FALSE, warning = FALSE}
amazon_joined %>%
  inner_join(nrc_positive, by = "word") %>%
  filter(gd_ind_position %in% c("Software Development Engineer", "Program Manager", "Software Engineer", "Operations Manager")) %>% 
  count(gd_ind_position, word, sort = TRUE) %>%
  filter(n > 10) %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n)) +
  geom_col(fill = "#00BFC4") +
  labs(title = "Positive words", x = NULL) +
  theme(text = element_text(size = 13)) +
  coord_flip() +
	facet_wrap(~ gd_ind_position, ncol = 4)
```

```{r fig 05, echo = FALSE, message = FALSE, warning = FALSE}
amazon_joined %>%
  inner_join(nrc_negative, by = "word") %>%
  filter(gd_ind_position %in% c("Software Development Engineer", "Program Manager", "Software Engineer", "Operations Manager")) %>% 
  count(gd_ind_position, word, sort = TRUE) %>%
  filter(n > 3) %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n)) +
  geom_col(fill = "#F8766D") +
  labs(title = "Negative words", x = NULL) +
  theme(text = element_text(size = 13)) +
  coord_flip() +
	facet_wrap(~ gd_ind_position, ncol = 4)
```

## Wordcloud

```{r fig 06, echo = FALSE, message = FALSE, warning = FALSE}
pal<-brewer.pal(8, "Dark2")
amazon_joined %>%
anti_join(stop_words, by = "word") %>%
count(word) %>%
with(wordcloud(word, n, max.words = 100, colors = pal, random.color = T))
```

## Positive and negative wordcloud

```{r fig 07, echo = FALSE, message = FALSE, warning = FALSE}
amazon_joined %>%
inner_join(get_sentiments("bing"), by = "word") %>%
count(word, sentiment, sort = TRUE) %>%
acast(word ~ sentiment, value.var = "n", fill = 0) %>%
comparison.cloud(colors = c("#F8766D", "#00BFC4"), max.words = 100)
```